version: '3.8'

services:
  frontend:
    container_name: frontend-container
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend-container
    build:
      context: ./server/video-editing-api
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - database
    networks:
      - app-network
    environment:
      MONGO_URI: mongodb://database:27017/VideoEditing

  database:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: