#version: "3.8"
#services:
  #app:
    #container_name: video-analysis
    #image: video-analysis
    #build:
      #context: ./client
      #target: production
    #ports:
      #- "5002:80"
version: '3.8'

services:
  video-editing-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - video-editing-api
