version: '3.8'

services:
  database:
    container_name: mongodb
    image: mongo
    command: mongod --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongo-network
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: 27017
  api:
    container_name: api-container
    image: anhhoang2910/api
    build:
      context: ./server/video-editing-api
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - database
    networks:
      - mongo-network
    environment:
      MONGO_URI: mongodb://database:27017/VideoEditing

  # init-mongo:
  #   container_name: init-mongo-container
  #   image: mongo
  #   command: mongo mongodb://mongodb:27017/VideoEditing /init-mongo.js
  #   volumes:
  #     - ./init-mongo.js:/init-mongo.js
  #   depends_on:
  #     - database
  #   networks:
  #     - mongo-network

  frontend:
    container_name: frontend-container
    image: anhhoang2910/frontend
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:80"
    networks:
      - mongo-network

volumes:
  mongodb_data:

networks:
  mongo-network: